# Generated by Django 4.2.7 on 2024-01-16 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_height_remove_user_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
