# Generated by Django 4.2.7 on 2024-01-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_repeatingworkout_remove_exercise_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='workout',
            name='repeatingWorkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.repeatingworkout'),
        ),
    ]
