# Generated by Django 4.2.7 on 2024-01-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_workout_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
