# STAGE 1
FROM node:21-alpine as builder

RUN mkdir /app
WORKDIR /app

COPY angular-app/package.json angular-app/package-lock.json /app/angular-app/

RUN npm install --prefix angular-app

COPY . /app

RUN npm run build --prefix angular-app -- --output-path=./dist/out

# STAGE 2

FROM nginx:1.25.3-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/angular-app/dist/out /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf